import Head from "next/head";
import { Image } from "@mantine/core";
import { Button } from "@mantine/core";
import { TextInput } from "@mantine/core";
import { useState, useEffect } from "react";
export default function Home() {
  const initialData = { email: "", password: "" };

  const [updateData, setUpdateData] = useState(initialData);
  const [formErrors, setFormErrors] = useState({});
  const [isSubmited, setIsSubmited] = useState(false);

  const handelChange = (e) => {
    const { type, value } = e.target;
    setUpdateData({ ...updateData, [type]: value });
    console.log(updateData);
  };

  const handelSubmit = (event) => {
    event.preventDefault();
    setFormErrors(checkValidation(updateData));
    setIsSubmited(true);
  };

  const checkValidation = (formValues) => {
    const errors = {};
    const emailRegex =
      /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;

    if (!formValues.email) {
      errors.email = " Email is required ! ";
    } else if (!emailRegex.test(formValues.email)) {
      errors.email = "Invalide email ! ";
    }
    if (!formValues.password) {
      errors.password = " Password is required ! ";
    } else if (formValues.password.length < 4) {
      errors.password = "Password must contain atleast 4 chacters ";
    } else if (formValues.password.length > 8) {
      errors.password = "Password can contain atmost 8 chacters ";
    }
    return errors;
  };

  useEffect(() => {
    if (Object.keys(formErrors).length === 0 && isSubmited) {
      console.log(updateData);
      alert(
        `if your email or password matches with our Database Enteries then you will get to LogedIn `
      );
    }
  }, [updateData]);

  return (
    <>
      <Head>
        <title> EC | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoIcon.jpg" />
      </Head>
      <div className=" w-screen flex flex-col h-screen md:flex-row">
        <div className="w-full  flex flex-col p-5 items-start h-auto md:bg-teal-50 h-screen ">
          <div className="mx-auto w-1/3">
            <Image
              src="https://engineerscradle.com/assets/Logo_lg.svg"
              className="max-w-full h-auto"
            />
          </div>

          <div className=" hidden md:flex mt-2 justify-center items-center p-10 w-full h-full">
            <div className="flex items-center justify-center w-3/5 ">
              <Image
                src="https://engineerscradle.com/assets/Auth/Login/EC_Login.svg"
                className="h-auto max-w-full "
              />
            </div>
          </div>
        </div>

        <div className="w-full h-full flex justify-center items-center md:h-screen p-10">
          <div className="flex absolute top-0 right-0 m-6  md:m-10 ">
            <Button
              variant="default"
              className="w-fit h-8 py-1 px-4 font-normal "
            >
              Sign Up
            </Button>
          </div>
          <div className="w-11/12 flex flex-col items-start md:w-4/5 ">
            <p className="font-bold text-2xl tracking-wide break-words">
              Welcome Back!
            </p>

            <form className="mt-5 break-words w-full " onSubmit={handelSubmit}>
              <TextInput
                label="Email"
                placeholder="example@gmail.com"
                className="mt-2 "
                type="email"
                value={updateData.email}
                onChange={handelChange}
              />
              <p className="text-red-700 my-2 ">{formErrors.email}</p>
              <TextInput
                label="Password"
                placeholder="Password"
                className="mt-2 text-sm "
                type="password"
                value={updateData.password}
                onChange={handelChange}
              />
              <p className="text-red-700 my-2 ">{formErrors.password}</p>
              <p className="mt-2 text-blue-500 break-words  ">
                Forgot Password ?
              </p>
              <div className="mt-2">
                <Button
                  variant="filled"
                  className="bg-blue-500  w-full  text-white"
                  type="submit"
                >
                  Login
                </Button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}
